<a href="https://colab.research.google.com/github/cabanissjaso/LJA_AdvancedPython_JC/blob/main/Jason_Cabaniss_Week_1_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 ### Jason Cabaniss

Please add your name to this markdown cell.

## Submitting your homework!

Two steps are required for this week's homework once you have completed it:

- __Share__ this notebook with _libraryjuicepresspython@gmail.com_ so it can be marked in Colab
- __Print as PDF__ and upload to the the week's homework submission location on the Library Juice Academy LMS

# Advanced Python - Week 1 Homework

(Be sure to save this to Drive before starting)

For this week we are going to practice requesting information from an API and manipulating it as JSON and as a Dataframe.

We are going to keep working with Collection Builder. Head over to the [Collection Builder Example Projects](https://collectionbuilder.github.io/cb-examples/browse.html) listing and find a site that interests you. Spend some time browsing the website to get acquainted with its contents before proceeding with the questions.

In [ ]:
#The Libraries we will need
import requests
import json
import pandas as pd
from random import randrange

In [ ]:
# @markdown **H1** Find the URL of for the  _metadata.json_ of your selected site and paste it in here.
json_cb_url = "https://lib410-spring2023.github.io/group-1/assets/data/metadata.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_url)
#all of the data from the sites
total_cb_data = response_cb.json()
#just the 'objects' indexed in the site
objects_cb_data = total_cb_data['objects']
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

**H2** Run the 'show random cell' a few times to get a sense of what kind of data is in your chosen site.

In [ ]:
#Run this a few times to see random entries in the JSON data that you retrieved.
random_entry = randrange(len(objects_cb_data))
print(json.dumps(objects_cb_data[random_entry],indent=2))

{
  "title": "Kell's Restaurant",
  "creator": "Ross, Marion Dean",
  "date": "1889",
  "description": "Image of Kell's Restaurant in downtown Portland, Oregon.",
  "subject": "restaurants; private (relating to property)",
  "location": "Portland; Multnomah County; Oregon",
  "latitude": "45.521697",
  "longitude": "-122.672432",
  "source": "<a href=\"https://oregondigital.org/concern/images/df67mb55n\"target=\"_blank\">Building Oregon - University of Oregon</a>",
  "type": "Image; Still Image",
  "format": "image/jpeg",
  "rights": "In Copyright",
  "reference_url": "https://lib410-spring2023.github.io/group-1/item.html?id=portland_kellsrestaurant_1889"
}

## Different Fields!

You can create any number of datafields and correpsonding values for those fields with a Collection Builder site. So the results from the output from the cell above will probably have wildly different results from [my site](https://elibtronic.github.io/AIL_Database/data.html) that we worked on in the Workalong notebook.


You can see all of these options from grabbing the _facets.json_ URL from a collection builder homepage. Find that URL for your selected site for **H3**

In [ ]:
# @markdown **H3** Find the URL of the facets.json for your selected site and paste it in here.
json_cb_facets_url = "https://lib410-spring2023.github.io/group-1/assets/data/facets.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_facets_url)
#all of the data from the sites
total_facet_data = response_cb.json()
#just the 'objects' indexed in the site
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

Run the cell below to see what the facets used for this site:

In [ ]:
print(json.dumps(total_facet_data,indent=2))

{
  "facets": [
    {
      "field": "subject",
      "terms": {
        "art house cinemas": 2,
        "bridges": 1,
        "caves": 1,
        "cemeteries": 2,
        "churches": 1,
        "forts": 1,
        "highways": 2,
        "historic houses": 3,
        "hotels": 4,
        "lighthouses": 3,
        "mills": 1,
        "private (relating to property)": 10,
        "public (relating to property)": 11,
        "restaurants": 1,
        "taverns": 1,
        "theater": 1,
        "waterfalls": 1
      }
    },
    {
      "field": "creator",
      "terms": {
        "angelus studio": 3,
        "boothby, wilbur f.": 1,
        "drew, earl m. and walter ross baumes willcox": 1,
        "foulkes, edward t.": 1,
        "gilman, davis c.": 1,
        "holford, william": 1,
        "johnson, ian p.": 1,
        "lawrence, ellis fuller": 1,
        "lawrence, holford": 1,
        "millwain, alexander w.": 1,
        "patterson, frank": 1,
        "patton post card co. (salem, or.)": 1,
        "pugh, walter d.": 1,
        "ross, marion dean": 2,
        "singley, b.l.": 1,
        "unknown": 5
      }
    },
    {
      "field": "format",
      "terms": {
        "image/jpeg": 21
      }
    }
  ]
}

**H3** Try to read the JSON that is displayed to the screen. What possible facets are there in the the data. Fill them in the markdown list in the cell below. Add as many entries as you need to describe the site

Facets in my site are:
- subject
- creator
- format

**H4** Which facet shows up the most for your selected site? Put your answer in the cell below

[link text](https://lib410-spring2023.github.io/group-1/browse.html#image%2Fjpeg$0)
This facet that shows up the most is image/jpeg it is used 21 times on my selected site. That's probably because every image entered is a JPEG!

**H5** Turn the site _metadata.json_ data into a dataframe by completing the cell below. Part of it is written for you. You just need to modify line 4.

In [ ]:
#H5

cb_data = pd.read_json(json_cb_url)
cb_normalized = pd.json_normalize(cb_data['objects'])
cb_normalized

,title,creator,date,description,subject,location,latitude,longitude,source,type,format,rights,reference_url
0,Eugene Pioneer Cemetery,Unknown,1872,Image of a tall white grave in the Eugene Pion...,cemeteries; public (relating to property),Eugene; Oregon; Lane County,44.041447,-123.076002,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
1,First Congregational Church,"Drew, Earl M. and Walter Ross Baumes Willcox",1925,Image of the Eugene First Congregational Churc...,art house cinemas; churches; private (relating...,Eugene; Oregon; Lane County,44.045367,-123.085618,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright - Educational Use Permitted,https://lib410-spring2023.github.io/group-1/it...
2,Heceta Lighthouse,Unknown,1957,Image of the south-facing side of the Heceta H...,lighthouses; hotels; historic houses; private ...,Florence; Oregon; Lane County,44.137364,-124.128132,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
3,Tillamook Lighthouse,Unknown,1881,Image of the north-facing side of the Tillamoo...,lighthouses; private (relating to property),Seaside; Oregon; Clatsop County,45.937236,-124.018868,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright - Educational Use Permitted,https://lib410-spring2023.github.io/group-1/it...
4,Crooked River Bridge,Angelus Studio,1880,Image of the highway bridge crossing Crooked R...,bridges; highways; public (relating to property),Terrebonne; Oregon; Deschutes County,44.392590,-121.194007,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
5,Oregon Caves,"Singley, B.L.",1899,Image of a man holding a lantern in the Ghost ...,caves; public (relating to property),Oregon Caves National Monument; Josephine Coun...,42.098120,-123.407456,"<a href ""https://www.loc.gov/item/2018651791/""...",Image; Still Image,image/jpeg,No Copyright - Public Domain,https://lib410-spring2023.github.io/group-1/it...
6,Pittock Mansion,"Foulkes, Edward T.",1970,Image of the front (northwestern) view of Pitt...,historic houses; public (relating to property),Portland; Multnomah County; Oregon,45.525161,-122.716264,"<a href ""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
7,Fort Stevens,"Gilman, Davis C.",1973,Image of a concrete battery located within For...,forts; public (relating to property),Warrenton; Clatsop County; Oregon Coast; Oregon,46.192547,-123.975336,"<a href ""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
8,Asahel Bush,"Boothby, Wilbur F.",1878,"Image of a house surrounded by trees, sitting ...",historic houses; public (relating to property),Salem; Marion County; Oregon,44.931426,-123.039263,"<a href ""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
9,Hwy 101,Unknown,1967,View from top of Cape Perpetua of Visitor Cent...,public (relating to property); highways,Oregon Coast; Lincoln County; Oregon,44.281021,-124.109498,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
10,Benson Hotel,Angelus Studio,1880,"View of Benson Hotel from Broadway and Oak, Po...",private (relating to property); hotels,Portland; Multnomah County; Oregon,45.521494,-122.678693,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
11,Yaquina Lighthouse,Unknown,1900,Exterior view of Yaquina Head lighthouse tower.,public (relating to property); lighthouses,Newport; Lincoln County; Oregon,44.676752,-124.079568,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
12,Elsinore Theater,"Lawrence, Holford; Lawrence, Ellis Fuller; Hol...",1926,View of the front of Elsinor Theater from the ...,private (relating to property); theater,Salem; Marion County; Oregon,44.938919,-123.037369,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright - Educational Use Permitted,https://lib410-spring2023.github.io/group-1/it...
13,Woolen Mill,"Pugh, Walter D.",1898,Exterior view of Woolen Mill,public (relating to property); mills,Salem; Marion County; Oregon,44.934955,-123.027134,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
14,Wolf Creek Tavern,"Patterson, Frank",1927,"Image of Wolf Creek Tavern, built in 1857.",taverns; private (relating to property),Wolf Creek; Josephine County; Oregon,42.695123,-123.396038,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
15,Multnomah Falls,"Patton Post Card Co. (Salem, Or.)",1915,Image of Multnomah Falls from below.,waterfalls; public (relating to property),Troutdale; Multnomah County; Oregon,45.575855,-122.115268,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,No Copyright - Public Domain,https://lib410-spring2023.github.io/group-1/it...
16,Lone Fir Cemetery,"Johnson, Ian P.",1855,"Image of large tombstone in Lone Fir Cemetery,...",cemeteries; public (relating to property),Portland; Multnomah County; Oregon,45.518151,-122.642152,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright - Educational Use Permitted,https://lib410-spring2023.github.io/group-1/it...
17,Hollywood Theater,Angelus Studio,1880,"Image of Hollywood Theatre on Sandy Blvd., Por...",art house cinemas; private (relating to property),Portland; Multnomah County; Oregon,45.535584,-122.620721,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
18,Merchants Hotel,"Ross, Marion Dean",1973,Image of Merchants hotel façade in downtown Po...,hotels; private (relating to property),Portland; Multnomah County; Oregon,45.524409,-122.673299,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
19,Kell's Restaurant,"Ross, Marion Dean",1889,Image of Kell's Restaurant in downtown Portlan...,restaurants; private (relating to property),Portland; Multnomah County; Oregon,45.521697,-122.672432,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
20,Geiser Hotel,"Millwain, Alexander W.",1889,"Image of Geiser Grand Hotel in Baker City, Ore...",hotels; private (relating to property),Baker City; Baker County; Oregon,44.776966,-117.829316,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...

In [ ]:
#Run this a few times to see random entries in your dataframe
cb_normalized.sample(10)

,title,creator,date,description,subject,location,latitude,longitude,source,type,format,rights,reference_url
20,Geiser Hotel,"Millwain, Alexander W.",1889,"Image of Geiser Grand Hotel in Baker City, Ore...",hotels; private (relating to property),Baker City; Baker County; Oregon,44.776966,-117.829316,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
10,Benson Hotel,Angelus Studio,1880,"View of Benson Hotel from Broadway and Oak, Po...",private (relating to property); hotels,Portland; Multnomah County; Oregon,45.521494,-122.678693,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
17,Hollywood Theater,Angelus Studio,1880,"Image of Hollywood Theatre on Sandy Blvd., Por...",art house cinemas; private (relating to property),Portland; Multnomah County; Oregon,45.535584,-122.620721,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
15,Multnomah Falls,"Patton Post Card Co. (Salem, Or.)",1915,Image of Multnomah Falls from below.,waterfalls; public (relating to property),Troutdale; Multnomah County; Oregon,45.575855,-122.115268,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,No Copyright - Public Domain,https://lib410-spring2023.github.io/group-1/it...
7,Fort Stevens,"Gilman, Davis C.",1973,Image of a concrete battery located within For...,forts; public (relating to property),Warrenton; Clatsop County; Oregon Coast; Oregon,46.192547,-123.975336,"<a href ""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
9,Hwy 101,Unknown,1967,View from top of Cape Perpetua of Visitor Cent...,public (relating to property); highways,Oregon Coast; Lincoln County; Oregon,44.281021,-124.109498,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
13,Woolen Mill,"Pugh, Walter D.",1898,Exterior view of Woolen Mill,public (relating to property); mills,Salem; Marion County; Oregon,44.934955,-123.027134,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
16,Lone Fir Cemetery,"Johnson, Ian P.",1855,"Image of large tombstone in Lone Fir Cemetery,...",cemeteries; public (relating to property),Portland; Multnomah County; Oregon,45.518151,-122.642152,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright - Educational Use Permitted,https://lib410-spring2023.github.io/group-1/it...
6,Pittock Mansion,"Foulkes, Edward T.",1970,Image of the front (northwestern) view of Pitt...,historic houses; public (relating to property),Portland; Multnomah County; Oregon,45.525161,-122.716264,"<a href ""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...
4,Crooked River Bridge,Angelus Studio,1880,Image of the highway bridge crossing Crooked R...,bridges; highways; public (relating to property),Terrebonne; Oregon; Deschutes County,44.392590,-121.194007,"<a href=""https://oregondigital.org/concern/ima...",Image; Still Image,image/jpeg,In Copyright,https://lib410-spring2023.github.io/group-1/it...

**H6** This is for bonus!
Try to write a pandas statement that will display your answer from **H4**. There are plenty of ways to do this, so feel free to use your imagination. What I have started for you here might not work, so feel free to change it as needed.

In [ ]:
cb_normalized[cb_normalized["format"] == "image/jpeg"].count()

##I feel like we could also have used a similar format found in the workalong section "Subject Counts".

title            21
creator          21
date             21
description      21
subject          21
location         21
latitude         21
longitude        21
source           21
type             21
format           21
rights           21
reference_url    21
dtype: int64


## All Done!

Congrats you are finished with this week's work. First save as PDF so that you can upload to the Course site then click the `Share` button above and enter `libraryjuicepresspython@gmail.com` so I can get a shared copy of your work.